server:
  port: 8769
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: turbine-service
turbine:
  aggregator:
    clusterConfig: default
  appConfig: eureka-client-one,eureka-client-two
  clusterNameExpression: new String("default")

management:
  security:
    enabled: false