server:
  port: 8762
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: eureka-client-one
logging:
  file: "logs/eureka-client-one.log"
management:
  security:
    enabled: false